#services:
#  pgvector-db:
#    image: ankane/pgvector:latest
#    container_name: pgvector-db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Manish@2009
#      POSTGRES_DB: springai
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgvector-data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # This auto-enables extensions
#    restart: unless-stopped
#
#volumes:
#  pgvector-data: